// lia-web/src/app/pages/login.component.ts
import { Component, OnInit, signal, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { AuthService } from '../core/services/auth.service';

@Component({
  standalone: true,
  selector: 'app-login',
  imports: [CommonModule],
  template: `
    <div class="login-container">
      <div class="login-card">
        <h1>Entrar</h1>
        <p class="subtitle">Faça login para acessar o LIA Web.</p>

        <button
          type="button"
          (click)="handleLogin()"
          [disabled]="isLoading()"
          class="login-btn">
          {{ isLoading() ? 'Entrando…' : 'Entrar (modo local)' }}
        </button>

        @if (error()) {
          <div class="error-msg">
            {{ error() }}
          </div>
        }

        <div class="info-text">
          Você escolheu <strong>evitar serviços externos</strong>. Este login cria
          uma sessão local (armazenada no navegador) e não usa Google/Supabase.
        </div>
      </div>
    </div>
  `,
  styles: [`
    .login-container {
      min-height: 100vh;
      background: #f9fafb;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 1rem;
    }
    .login-card {
      width: 100%;
      max-width: 28rem;
      border-radius: 0.75rem;
      background: white;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      border: 1px solid #e5e7eb;
      padding: 1.5rem;
    }
    h1 {
      font-size: 1.5rem;
      font-weight: bold;
      color: #111827;
      margin: 0 0 0.25rem;
    }
    .subtitle {
      font-size: 0.875rem;
      color: #6b7280;
      margin: 0 0 1.5rem;
    }
    .login-btn {
      margin-top: 1.5rem;
      width: 100%;
      border-radius: 0.5rem;
      background: #8b5cf6;
      padding: 0.5rem 1rem;
      color: white;
      font-weight: 600;
      border: none;
      cursor: pointer;
    }
    .login-btn:hover:not(:disabled) {
      opacity: 0.95;
    }
    .login-btn:disabled {
      opacity: 0.6;
      cursor: not-allowed;
    }
    .error-msg {
      margin-top: 1rem;
      border-radius: 0.5rem;
      border: 1px solid #fecaca;
      background: #fef2f2;
      padding: 0.75rem;
      font-size: 0.875rem;
      color: #b91c1c;
    }
    .info-text {
      margin-top: 1rem;
      font-size: 0.75rem;
      color: #6b7280;
    }
  `]
})
export class LoginComponent implements OnInit {
  protected readonly error = signal<string | null>(null);
  protected readonly isLoading = signal(false);

  private authService = inject(AuthService);
  private router = inject(Router);

  ngOnInit(): void {
    if (this.authService.isAuthenticated) {
      this.router.navigate(['/dashboard'], { replaceUrl: true });
    }
  }

  async handleLogin(): Promise<void> {
    this.error.set(null);
    this.isLoading.set(true);

    try {
      await this.authService.signInLocal();
      await this.router.navigate(['/dashboard'], { replaceUrl: true });
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Erro inesperado';
      this.error.set(message);
      this.isLoading.set(false);
    }
  }
}

// src/pages/Login.tsx
import { useState } from 'react'

import { signInLocal } from '@/lib/auth'
import { useNavigate } from 'react-router-dom'

export function LoginPage() {
  const navigate = useNavigate()
  const [error, setError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)

  async function handleLoginWithGoogle() {
    setError(null)
    setIsLoading(true)

    try {
      // Modo local: sem serviços externos. Criamos uma sessão e seguimos para o dashboard.
      await signInLocal()
      navigate('/dashboard', { replace: true })
    } catch (e) {
      const message = e instanceof Error ? e.message : 'Erro inesperado'
      setError(message)
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center px-4">
      <div className="w-full max-w-md rounded-xl bg-white shadow-sm border border-gray-200 p-6">
        <h1 className="text-2xl font-bold text-gray-900">Entrar</h1>
        <p className="text-sm text-gray-600 mt-1">
          Faça login para acessar o LIA Web.
        </p>

        <button
          type="button"
          onClick={handleLoginWithGoogle}
          disabled={isLoading}
          className="mt-6 w-full rounded-lg bg-primary-purple px-4 py-2 text-white font-semibold hover:opacity-95 disabled:opacity-60"
        >
          {isLoading ? 'Entrando…' : 'Entrar (modo local)'}
        </button>

        {error ? (
          <div className="mt-4 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
            {error}
          </div>
        ) : null}

        <div className="mt-4 text-xs text-gray-500">
          Você escolheu <strong>evitar serviços externos</strong>. Este login cria
          uma sessão local (armazenada no navegador) e não usa Google/Supabase.
        </div>
      </div>
    </div>
  )
}
